name: "Semantic Release"
description: "Custom implementation of Semantic Release able to handle per project releases"

inputs:
  PROJECT_NAME:
    description: "Name of the project to release"
    required: true
  PROJECT_DIRECTORY:
    description: "Folder patht to the project directory"
    required: true
  BRANCHES:
    description: "List of branches for semantic release"
    required: false
    default: main
  GITHUB_TOKEN:
    description: "Token to use for Github"
    required: true
  TEMPLATE_FILE:
    description: "Semantic release template file"
    required: false
    default: .github/templates/github/semantic_release/.releaserc.json.template
  DRY_RUN:
    description: "Should we execute in a dry run mode?"
    required: false
    default: true

outputs:
  new_release_version:
    description: "New TAG attached to the Semantic Release version"
    value: ${{ steps.semantic-release.outputs.new_release_version }}
  new_release_published:
    description: "Whether a new release was published"
    value: ${{ steps.semantic-release.outputs.new_release_published }}
  new_release_notes:
    description: "Release notes for Semantic Release"
    value: ${{ steps.export-released-notes.outputs.new_release_notes }}

runs:
  using: "composite"
  steps:
    - name: "Creating Project Related Template"
      id: semantic-release-template
      shell: bash
      run: |
        # creating project name variables
        export PROJECT_NAME_UPPER=$(echo ${{ inputs.PROJECT_NAME }} | tr 'a-z' 'A-Z')
        export PROJECT_NAME_LOWER=$(echo ${{ inputs.PROJECT_NAME }} | tr 'A-Z' 'a-z')
        # populating project specific template for the semantic release
        envsubst '${PROJECT_NAME_UPPER} ${PROJECT_NAME_LOWER}' < ${{ inputs.TEMPLATE_FILE }} > ${{ inputs.PROJECT_DIRECTORY }}/.releaserc.json

        # Verify the template was created successfully
        if [ ! -f "${{ inputs.PROJECT_DIRECTORY }}/.releaserc.json" ]; then
          echo "::error::Failed to create .releaserc.json template"
          exit 1
        fi

        # Show the generated template for debugging
        echo "Generated semantic-release config:"
        cat ${{ inputs.PROJECT_DIRECTORY }}/.releaserc.json

    - name: "Setup Node"
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: "Configure Git user"
      shell: bash
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: "Install semantic-release dependencies"
      shell: bash
      run: |
        echo "Installing semantic-release dependencies..."
        cd ${{ inputs.PROJECT_DIRECTORY }}
        npm install --no-package-lock --no-save \
          semantic-release@24.1.0 \
          @semantic-release/commit-analyzer \
          @semantic-release/release-notes-generator \
          @semantic-release/changelog \
          @semantic-release/github \
          @semantic-release/git \
          @semantic-release/exec \
          conventional-changelog-conventionalcommits@5.0.0

    - name: "Run Semantic Release"
      id: semantic-release
      uses: cycjimmy/semantic-release-action@v3.4.1
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        branches: ${{ inputs.BRANCHES }}
        dry_run: ${{ inputs.DRY_RUN }}
        working_directory: ${{ inputs.PROJECT_DIRECTORY }}
        extra_plugins: |
          @semantic-release/commit-analyzer
          @semantic-release/release-notes-generator
          @semantic-release/changelog
          @semantic-release/github
          @semantic-release/git
          @semantic-release/exec
          conventional-changelog-conventionalcommits@5.0.0

    - name: "Export released version"
      id: export-released-version
      shell: bash
      run: |
        if [ "${{ steps.semantic-release.outputs.new_release_version }}" != "" ]; then
          echo "new_release_version=${{ steps.semantic-release.outputs.new_release_version }}" >> $GITHUB_OUTPUT
          echo "New release version: ${{ steps.semantic-release.outputs.new_release_version }}"
        else
          echo "No new version released"
        fi

    - name: "Export release notes"
      id: export-released-notes
      shell: bash
      run: |
        if [ "${{ steps.semantic-release.outputs.new_release_notes }}" != "" ]; then
          RELEASE_NOTES="${{ steps.semantic-release.outputs.new_release_notes }}"
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          echo "new_release_notes=${RELEASE_NOTES}" >> $GITHUB_OUTPUT
          echo "Release notes captured successfully"
        else
          echo "No release notes available"
          echo "new_release_notes=No release notes available" >> $GITHUB_OUTPUT
        fi

    - name: "Release summary"
      if: steps.semantic-release.outputs.new_release_published == 'true'
      shell: bash
      run: |
        echo "A new release has been published!"
        echo "Version: ${{ steps.semantic-release.outputs.new_release_version }}"
        echo "Major: ${{ steps.semantic-release.outputs.new_release_major_version }}"
        echo "Minor: ${{ steps.semantic-release.outputs.new_release_minor_version }}"
        echo "Patch: ${{ steps.semantic-release.outputs.new_release_patch_version }}"
